### ISSUE TITLE
Remove UnitedRPMs/libmad

### ISSUE THREAD

**Issue by ghost** [UnitedRPMs/issues#1]
Hi,

Since MP3 patents expired, this package is [already](https://admin.fedoraproject.org/pkgdb/package/rpms/libmad/) in F24-F27 repositories and I guess this one may be dropped.

However, `lame-libs` and `mpg123` are not in F24, they should be kept at least a couple of months yet.

Dependent packages which rely on `libmad-devel` have some restriction related conditional and may be revised to move these lines out of these blocks:

- UnitedRPMs/deadbeef
- UnitedRPMs/idjc
- UnitedRPMs/sox-plugins-freeworld

There is also a mention about restrictions in UnitedRPMs/vlc spec which might be updated too, but it's just cosmetic.

Regards.

**Comment by kuboosoft** [comment]
@fdelapena the mitigation is minimal, because is the same version ... can you make the changes in deadbeef, idjc and sox-plugins-freeworld? with vlc I need update live555 then I can make the change here...

**Comment by kuboosoft** [comment]
@fdelapena I completely forgot!, mpg123 is out-day in fedora, we can't drop our mpg123 if fedora doesn't update to 1.24.0; it will broke various dependencies in UnitedRPMs. I will try suggest it bugzilla.

**Comment by ghost** [comment]
The upstream monitoring bot already filed a bug: https://bugzilla.redhat.com/show_bug.cgi?id=1428195
mpg123 didn't land into FC24 yet, and I hope it won't. However, libmad seems safe, no updated in years. Maybe in two months they fix that bug, I'm going to monitor it.

**Comment by kuboosoft** [comment]
Hi, today I will delete libmad in UnitedRPMs, Fedora has the package for F24... isn't necessary maintain here.
