### ISSUE TITLE
Appstream data for UnitedRPMs, is necessary?

### ISSUE THREAD

**Issue by kuboosoft** [UnitedRPMs/issues#10]
We have great software and considering that a lot of the packages in UnitedRPMs are media player front-ends, converters and things, it'd make it a lot easier for users if these were also listed in Gnome software.  I believe we can write appstream data files for all packages that could be listed in Gnome software. We need help and a volunteers for it. Here the repository for volunters. https://github.com/UnitedRPMs/unitedrpms-appstream-data

with the next line we can generate it, but it doesn't work 100% for us, because it excludes some desktop applications...

`# appstream-builder --packages-dir=/home/makerpm/unitedrpms/packages/ --output-dir=/tmp/asb-md --basename="unitedrpms" --origin="unitedrpms" --enable-hidpi --cache-dir=/tmp/asb-cache --max-threads=6 --temp-dir=/tmp/asb-icons`

Other option (difficult) The best choice is make appdata in each package without appdata, but only packages with a .desktop file or complements. The appdata of vlc is a great example :)

https://fedoraproject.org/wiki/Packaging:AppData

**Comment by sergiomb2** [comment]
https://pkgs.rpmfusion.org/cgit/free/rpmfusion-free-appstream-data.git/tree/update-appdata-rpmfusion-free.sh  help you ?

**Comment by kuboosoft** [comment]
@sergiomb2 is the same to:
`# appstream-builder --packages-dir=/home/makerpm/unitedrpms/packages/ --output-dir=/tmp/asb-md --basename="unitedrpms" --origin="unitedrpms" --enable-hidpi --cache-dir=/tmp/asb-cache --max-threads=6 --temp-dir=/tmp/asb-icons`

I already made it; but for some reason it exclude various packages (the majority). I don't understand. Maybe we need other way.

**Comment by kuboosoft** [comment]
I tested  in Fedora 25 and it failed... but it works now hahaha

**Comment by sergiomb2** [comment]
so you could help me update appstream in RPMFusion some time to time hahaha

**Comment by kuboosoft** [comment]
@sergiomb2 why not? you can use it.... in the repository will be include the updated metadata. Only I need make some changes in our sync tool adding some lines; then in each sync in urpms it update the git metadata repository. Also I will add "weak dependency/Recommends:..." in the [rpm repository](https://github.com/UnitedRPMs/unitedrpms). I maybe a "Provides:rpmfusion..metadata*free/no" in our [rpm with the metadata](https://github.com/UnitedRPMs/unitedrpms-appstream-data). I am not use Gnome Software but our users need a simple way to find our packages...

**Comment by ghost** [comment]
Hi @kuboosoft @sergiomb2 @paulcarroty , I know this repo is inactive since 2022, but I was cleaning old assignments including those on closed issues (visible with the following filter: https://github.com/issues/assigned?q=assignee%3A%40me ) and this one is the only hanging where I don't have writing permissions to unassign myself, so if anybody still have permissions on this repo to do this, I'd appreciate it. Thanks!
