### ISSUE TITLE
MPV lastest update is broken

### ISSUE THREAD

**Issue by Kcchouette** [UnitedRPMs/issues#12]
Latest version: ```mpv x86_64 1:0.27.0-2.gitd18f7bb.fc26 unitedrpms```

Error when launching mpv:
```
mpv: relocation error: mpv: symbol avio_read_partial, version LIBAVFORMAT_57 not defined in file libavformat.so.57 with link time reference
```

**Comment by kuboosoft** [comment]
Please provides the next info:

```
rpm -q ffmpeg

mpv

dnf repolist 
```

**Comment by Kcchouette** [comment]
I close the issue as it fixes when I update using `--allowerasing --best`

**Comment by kuboosoft** [comment]
@Kcchouette "--allowerasing --best" mmm isn't correct way; we are updating mpv...

**Comment by Kcchouette** [comment]
@kuboosoft the issue was on ffmpeg or x264 package that were not up to date to the version of the UnitedRPM but up to date to the version of fedora official repo.

**Comment by kuboosoft** [comment]
@Kcchouette Are you using rpmfusion? because fedora repo doesn't include mpv, ffmpeg or x264...

**Comment by Kcchouette** [comment]
@kuboosoft indeed

**Comment by kuboosoft** [comment]
@Kcchouette The updated mpv will solve the problem (12 hours); here the real problem "release in rpmfusion, same to the release in unitedrpms ) funny because our mpv was built with ffmpeg-3.4-1 ;)
