### ISSUE TITLE
F27: incompatible gstreamer1-plugins-bad-free with gnome-control-center 

### ISSUE THREAD

**Issue by NNois** [UnitedRPMs/issues#13]
Hi, with unitedrpms and fedora 27, after installing "la capitaine icons" and gstreamer1 from your repos, the gnome-control center report an error and doesn't launch:

`gnome-control-center
gnome-control-center: symbol lookup error: /lib64/libwebkit2gtk-4.0.so.37: undefined symbol: gst_gl_display_egl_new_with_egl_display`

here's another user hitting the same bug
https://bugzilla.redhat.com/show_bug.cgi?id=1499466
and https://bugzilla.redhat.com/show_bug.cgi?id=1471810

**Comment by kuboosoft** [comment]
@NNois Can you test it; I am using webkitgtk4 and our updated gstreamer1-plugins-bad-free without problem in F27... Also a new update for "la capitaine icons" comes in the next 12 hours ;)

```
/usr/bin/gtk-update-icon-cache /usr/share/icons/la-capitaine-icon-theme

su

/usr/bin/gtk-update-icon-cache /usr/share/icons/la-capitaine-icon-theme
```

Now close session or reboot...

**Comment by kuboosoft** [comment]
@NNois [Issue solved](https://unitedrpms.sourceforge.io/x86_64/repoview/gstreamer1-plugins-bad-free.html), Enjoy! haha

```
su
dnf clean all && dnf -y update
```

**Comment by sergiomb2** [comment]
I think dnf --refresh already works : 

    dnf -y update --refresh
