### ISSUE TITLE
Kodi 17.5 Bluray Menu Playback Fails

### ISSUE THREAD

**Issue by mmcnutt** [UnitedRPMs/issues#14]
kodi-17.5-3.git5bd45ab.fc26.x86_64
libbluray-1.0.1-1.fc26.x86_64

I can playback bluray without menus - but kodi.log shows a demux creation error when trying to use menus (I have libbluray-bdj etc installed)

`15:38:45.564 T:140448763603264  NOTICE: VideoPlayer: Opening: bluray://%2frun%2fmedia%2fmatt%2fSPIDER-MAN_HOMECOMING%2f/BDMV/MovieObject.bdmv
15:38:45.564 T:140448763603264 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
15:38:45.565 T:140447274002176  NOTICE: Creating InputStream
15:39:29.393 T:140447274002176  NOTICE: VideoPlayer: playing a file with menu's
15:39:29.393 T:140447274002176  NOTICE: Creating Demuxer
15:39:29.393 T:140447274002176 WARNING: CDVDInputStreamBluray - unhandled libbluray event 33 [param 3]
15:39:29.786 T:140447274002176   ERROR: Open - error probing input format, bluray://%2frun%2fmedia%2fmatt%2fSPIDER-MAN_HOMECOMING%2f/BDMV/MovieObject.bdmv
15:39:29.786 T:140447274002176   ERROR: OpenDemuxStream - Error creating demuxer`

**Comment by kuboosoft** [comment]
@mmcnutt ; thanks again. Can you test it... https://github.com/UnitedRPMs/issues/releases/tag/kodi ; I enabled the internal libbluray

`dnf -y reinstall *.rpm`

**Comment by mmcnutt** [comment]
this build would not read the disc at all - it showed it as listed, but play disc did nothing.

`09:34:51.995 T:139919915227456 WARNING: Create - unsupported protocol(bluray) in bluray://%2frun%2fmedia%2fmatt%2fSPIDER-MAN_HOMECOMING%2f/root
09:34:51.995 T:139919915227456   ERROR: CGUIWindowVideoBase::ShowPlaySelection - Failed to get play directory for bluray://%2frun%2fmedia%2fmatt%2fSPIDER-MAN_HOMECOMING%2f/root
09:34:51.997 T:139919915227456  NOTICE: VideoPlayer: Opening: /run/media/matt/SPIDER-MAN_HOMECOMING/BDMV/index.bdmv
09:34:51.997 T:139919915227456 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
09:34:51.997 T:139918156232448  NOTICE: Creating InputStream
09:34:51.998 T:139918156232448  NOTICE: Creating Demuxer
09:34:51.998 T:139918156232448   ERROR: Open - error probing input format, /run/media/matt/SPIDER-MAN_HOMECOMING/BDMV/index.bdmv
09:34:51.998 T:139918156232448   ERROR: OpenDemuxStream - Error creating demuxer`


The difference now seems to be that bluray is a completely unsupported format

**Comment by kuboosoft** [comment]
@mmcnutt  mmm, ok, can you test the current version in libbluray? here https://github.com/UnitedRPMs/issues/releases/tag/libbluray

```
su

dnf -y remove kodi && dnf -y install kodi

dnf -y install libbluray*.rpm
```

Also, Do you have the keys libbluray for decryption? read [here](https://negativo17.org/bluray-playback-and-ripping-on-fedora-aacs-bd-bd-j/)...

**Comment by mmcnutt** [comment]
Same errors now as the original bug report.

Yes my decryption is all good - I can decrypt the movies just fine, the movies play without the menus.

(I decrypt by redirecting to makemkv libraries, as I find this more reliable for recent discs)

**Comment by kuboosoft** [comment]
mmm bad; I found Kodi 18 has improved with libbluray and menus... We need wait for a new version for a full support in menus in bluray...

**Comment by mmcnutt** [comment]
Any chance of packaging a Kodi18 snapshot to find out?

I haven't compiled kodi since it changed it's build system - now might be as good a time as any to give it a try I guess

**Comment by kuboosoft** [comment]
@mmcnutt you only need change the version and the commit in our [.spec ](https://github.com/UnitedRPMs/kodi)and obtain kodi 18; but Kodi 18 is alpha... it support the external ffmpeg 3.4. I can't touch yet kodi if the pvr-addons isn't compatibles with kodi 18.

**Comment by mmcnutt** [comment]
I followed the kodi wiki guide to patch the rpmfusion src rpm with libdvdread and bluray menu playback works correctly. You might want to compare what is different between your build and theirs

**Comment by kuboosoft** [comment]
@mmcnutt I disabled the internal libdvd; can you test it... https://github.com/UnitedRPMs/issues/releases/tag/kodi

`dnf -y reinstall *.rpm`

**Comment by mmcnutt** [comment]
Sorry, I have not been home

Yes this appears to work correctly with the external libbluray

**Comment by kuboosoft** [comment]
The update also works fine? we can close it?
