### ISSUE TITLE
audacity-freeworld is fail to load ffmpeg libs in fedora 27

### ISSUE THREAD

**Issue by pda0** [UnitedRPMs/issues#15]
When I try to specify the libavformat.so library nothing happens. This formu post offers to build without dynamic loading: https://forum.audacityteam.org/viewtopic.php?f=48&t=97662

**Comment by kuboosoft** [comment]
@pda0 Can you share more information?

```
rpm -q audacity-freeworld

dnf provides audacity-freeworld
```

**Comment by pda0** [comment]
Sure.

$ rpm -q audacity-freeworld
audacity-freeworld-2.2.0-2.gitd6ee9bf.fc27.x86_64

$ LC_ALL=C dnf provides audacity-freeworld
Last metadata expiration check: 0:00:52 ago on Thu Nov 30 15:46:47 2017.
audacity-freeworld-2.2.0-2.gitd6ee9bf.fc27.x86_64 : Multitrack audio editor
Repo        : @System
Matched from:
Provide    : audacity-freeworld = 2.2.0-2.gitd6ee9bf.fc27

audacity-freeworld-2.2.0-3.gitd6ee9bf.fc27.x86_64 : Multitrack audio editor
Repo        : unitedrpms
Matched from:
Provide    : audacity-freeworld = 2.2.0-3.gitd6ee9bf.fc27

audacity-freeworld-2.1.3-4.fc27.x86_64 : Multitrack audio editor
Repo        : rpmfusion-free
Matched from:
Provide    : audacity-freeworld = 2.1.3-4.fc27

OK. I updated audacity to version 2.2.0-3 and it seems there is no more problem.

**Comment by kuboosoft** [comment]
Ok, Can we close the issue?

**Comment by pda0** [comment]
Yes, I think so.
