### ISSUE TITLE
Issue with sourceforge repo - Bad repomd file.

### ISSUE THREAD

**Issue by satrac** [UnitedRPMs/issues#16]
# dnf reposync --repo unitedrpms --verbose
Loaded plugins: builddep, config-manager, copr, debug, debuginfo-install, download, generate_completion_cache, needs-restarting, playground, repoclosure, repograph, repomanage, reposync
DNF version: 2.7.5
cachedir: /var/cache/dnf
Cannot download 'https://sourceforge.net/projects/unitedrpms/files/27/x86_64/': repomd.xml parser error: Element <repomd> was not found - Bad repomd file.
Failed to synchronize cache for repo 'unitedrpms', disabling.

**Comment by kuboosoft** [comment]
@satrac Don't worry, the repository is back online. 

`dnf clean all && dnf -y update`

**Comment by satrac** [comment]
Thank you, much apreciated!
