### ISSUE TITLE
flatpak support

### ISSUE THREAD

**Issue by kuboosoft** [UnitedRPMs/issues#18]
Actually UnitedRPMs makes rpms; why not flatpak from our rpms? the point is, we need help with new maintainers (Is hard job). More information, the next days.

**Comment by paulcarroty** [comment]
https://github.com/flathub is highly active now. No sense to compete with them.

But you can adapt your binary apps to their runtime.

* https://linux.die.net/man/1/readelf

* https://nixos.org/patchelf.html

* https://github.com/flathub?utf8=%E2%9C%93&q=sdk&type=&language=

**Comment by kuboosoft** [comment]
@paulcarroty Why flathub is the unique option? also we can make snaps (sounds fine)...  I call it a bonus from our rpms... But to future...

**Comment by paulcarroty** [comment]
Snaps sucks. You will understand just after looking under the hood.

**Comment by kuboosoft** [comment]
@paulcarroty Funny but; I don't like 'flatpaks', 'snaps'... We can't compare a package built natively... But we are open when 'flatpaks' or 'snaps'... or others; when the options will ready and  matures. In a flatpak  you have problems un-existent in natives packages... The unique package who I checked and works fine, was spotify for my old Laptop running Debian... Generally packages made in webkit, chromium, electron and similars works fine. Any volunteer is welcome; We could say we have the infrastructure for it.

**Comment by paulcarroty** [comment]
> Funny but; I don't like 'flatpaks', 'snaps'
Cool, you do **especially** what Microsoft want: when they buy Github many linuxoids doing distrowars, packagewars, new music players (KDE started new less than month ago) or just... waiting. 

In near future I will try to integrate Brackets into Flathub.

**Comment by kuboosoft** [comment]
I do not worry about github; and if Microsoft wants a distro linux; I can to package if they remunerate me, hahaha. I am open if MS pay my time... ;) But we ready; if the politics change in github (1-2 days to migrate our repositories).

[Literal](https://natfriedman.github.io/hello/)...

> At the same time, I understand that there is some healthy skepticism in the community, so I wanted to be absolutely clear about two things:
> 
> GitHub will operate independently as a community, platform, and business. This means that GitHub will retain its developer-first values, distinctive spirit, and open extensibility. We will always support developers in their choice of any language, license, tool, platform, or cloud.
> 
> GitHub will retain its product philosophy. We love GitHub because of the deep care and thoughtfulness that goes into every facet of the developer’s experience. I understand and respect this, and know that we will continue to build tasteful, snappy, polished tools that developers love.
> 
> I’m not asking for your trust, but I’m committed to earning it. I can’t wait to help make the GitHub platform and community that’s special to all of us even greater. att Nat

I will give the benefit of the doubt....

Brackets? We need help with Brackets; I reported a bug in 'brackets' on 2016, without solution yet... Our package is out-date... If you have F24 compiles fine hahaha
