### ISSUE TITLE
Leiningen has a typo in the /usr/bin/lein

### ISSUE THREAD

**Issue by 50574E** [UnitedRPMs/issues#20]
The version is supposed to be 2.8.1 not 2.6.1, I would do a pull request but I don't see a place where I can. The fix is literally just change one letter. Otherwise you will keep getting:

Error: Could not find or load main class clojure.main

**Comment by kuboosoft** [comment]
Thanks for the report; the issue is a old source.

**Comment by kuboosoft** [comment]
@50574E Thanks for the report; the issue is a [old source](https://github.com/UnitedRPMs/leiningen). A update is ready in our repositories.  Please check it. 

`su `
`dnf clean all && dnf -y update`
