### ISSUE TITLE
libass soname change in F29

### ISSUE THREAD

**Issue by mattiaverga** [UnitedRPMs/issues#24]
I'm having problems in upgrading to F29 because some packages (vlc and handbrake) still require libass.so.5 while F29 provides libass.so.9.
A rebuild of those packages is needed.

**Comment by mattiaverga** [comment]
Sorry, I've just seen that unitedrpms repo has Fedora version number hardcoded in its configuration file.
I've changed the configuration to F29 and now it's ok.

**Comment by kuboosoft** [comment]
@mattiaverga we have a rpm with the repository, please use it... We have support for F27-F30... You don't need to change the configuration because is automatic...
https://unitedrpms.github.io/#repository

**Comment by mattiaverga** [comment]
@kuboosoft I had the rpm installed, but the unitedrpms.repo file had hardcoded the Fedora version:
`baseurl=https://sourceforge.net/projects/unitedrpms/files/28/x86_64/`

so running `dnf system-upgrade` still used the F28 repository. I had to uninstall the unitedrpms rpm and then reinstall it with:
`dnf -y install https://github.com/UnitedRPMs/unitedrpms/releases/download/9/unitedrpms-29-9.fc29.noarch.rpm`
because before the system upgrade the macros in the command you suggest on your site still translates to F28.

I think you should change the url in the repofile to something like:
`baseurl=https://sourceforge.net/projects/unitedrpms/files/$releasever/$basearch/`

**Comment by kuboosoft** [comment]
@mattiaverga https://bugzilla.redhat.com/show_bug.cgi?id=1636743 ; as emergency we changed a " hardcoded Fedora version" but we reverted the change... https://github.com/UnitedRPMs/unitedrpms/blob/master/unitedrpms.spec#L48
