### ISSUE TITLE
Build ffmpeg with libdav1d enabled (for AV1 support)

### ISSUE THREAD

**Issue by TheDcoder** [UnitedRPMs/issues#26]
I see that `ffmpeg` from UnitedRPMs doesn't have `libdav1d` enabled, it is required for AV1 video playback in `mpv`. Someone also mentioned that it needs to be a *recent* version of ffmpeg which has support for `libdav1d`.

None of this knowledge is my own, but is a result of me complaining about not being able to play AV1 video at `#mpv in freenode`...

**Comment by kuboosoft** [comment]
@TheDcoder Hi; thanks for the report. The changes comes in the next hours.

**Comment by TheDcoder** [comment]
@kuboosoft Awesome! Can I expect this library to be enabled in the next/upcoming update? :smile:

**Comment by kuboosoft** [comment]
@TheDcoder sure; we are testing it... Each ".so" bump requires a massive rebuild...
https://github.com/UnitedRPMs/dav1d
https://github.com/UnitedRPMs/ffmpeg

**Comment by kuboosoft** [comment]
@TheDcoder . AV1 support enabled now! Enjoy!

**Comment by TheDcoder** [comment]
Awesome! Thanks :smile:
