### ISSUE TITLE
pulseaudio-module-bluetooth x86_64 12.2-7.fc29 broken dependencies

### ISSUE THREAD

**Issue by larieu** [UnitedRPMs/issues#29]
At install/update this dependency issue occur

 Problem: problem with installed package libfdk-aac-1:0.1.6-2.fc29.x86_64
  - installed package libfdk-aac-1:0.1.6-2.fc29.x86_64 obsoletes fdk-aac < 1:0.1.6-2.fc29 provided by fdk-aac-2.0.0-3.fc29.x86_64
  - package libfdk-aac-1:0.1.6-2.fc29.x86_64 obsoletes fdk-aac < 1:0.1.6-2.fc29 provided by fdk-aac-2.0.0-3.fc29.x86_64
  - package pulseaudio-module-bluetooth-12.2-7.fc29.x86_64 requires libfdk-aac.so.2()(64bit), but none of the providers can be installed
  - cannot install the best candidate for the job
================================================================================
 Package                        Arch      Version           Repository     Size
================================================================================
Installing:
 pulseaudio-module-bluetooth    x86_64    12.2-1.fc29       fedora         75 k
Skipping packages with broken dependencies:
 pulseaudio-module-bluetooth    x86_64    12.2-7.fc29       unitedrpms     77 k

Transaction Summary
================================================================================
Install  1 Package
Skip     1 Package

**Comment by kuboosoft** [comment]
@larieu Sorry isn't problem of UnitedRPMs, please choice Negativo17 or UnitedRPMs repository. Also you can report it in Negativo17. Good luck.
https://github.com/negativo17/libfdk-aac/blob/master/libfdk-aac.spec#L13
https://github.com/negativo17/libfdk-aac/blob/master/libfdk-aac.spec#L2
