### ISSUE TITLE
Problem with repo_gpgcheck=1

### ISSUE THREAD

**Issue by ondrejholy** [UnitedRPMs/issues#3]
The repo data are downloaded the first time on my Fedora rawhide after adding the repository:
```
$ sudo dnf update --refresh -vvv
(...)
Importing GPG key 0x5250AEF3:
 Userid     : "The UnitedRPMs Project (Key for UnitedRPMs infrastructure) <unitedrpms@protonmail.com>"
 Fingerprint: 36EB EB08 D346 B0A8 5B58 E140 EE78 8F49 5250 AEF3
 From       : /etc/pki/rpm-gpg/URPMS-GPG-PUBLICKEY-Fedora-24
Is this ok [y/N]: y
Repo unitedrpms: imported key 0xEE788F495250AEF3.
unitedrpms                                                                                                                    254 kB/s | 693 kB     00:02    
not found deltainfo for: unitedrpms
not found updateinfo for: unitedrpms
unitedrpms: using metadata from Thu May 25 01:11:34 2017 CEST.
```

However, it fails the second time with "Bad GPG signature":
```
$ sudo dnf update --refresh -vvv
(...)
Cannot download 'https://raw.githubusercontent.com/UnitedRPMs/unitedrpms.github.io/master/mirrorlist_F$releasever_x86_64.txt': repomd.xml GPG signature verification error: Bad GPG signature.
Failed to synchronize cache for repo 'unitedrpms', disabling.
```

It works correctly if I comment out "repo_gpgcheck=1". Don't you have any idea what is wrong? I've seen this problem also on one device with F26...

**Comment by kuboosoft** [comment]
mmm very strange, please provide the next:

`rpm -q unitedrpms`

now

`dnf clean all && dnf -y update`

`rpm -q unitedrpms`

Remember you have rawhide... we need update gstreamer1 plugins... I am testing the plugins now ;)

**Comment by ondrejholy** [comment]
Ha, `dnf clean all && dnf update` works nicely, however, `dnf update --refresh` fails, so I suppose something is probably wrong in `dnf` and not in your repo file, what do you think?

```
$ rpm -q unitedrpms
unitedrpms-27-3.fc27.noarch

$ dnf clean all && dnf update
...    
unitedrpms                                                                                                                    296 kB/s | 692 kB     00:02    
...
Last metadata expiration check: 0:00:00 ago on Fri May 26 08:40:46 2017 CEST.
Dependencies resolved.
Nothing to do.
Complete!

$ dnf update --refresh
...
Failed to synchronize cache for repo 'unitedrpms', disabling.
...

$ dnf clean all && dnf update
...
unitedrpms                                                                                                                    287 kB/s | 692 kB     00:02    
...
```

**Comment by sergiomb2** [comment]
yeah , I'm also trying track this bug, dnf  refresh etc use always same cache . 

`dnf --releasever=24 --disablerepo='*' --enablerepo=unitedrpms repoquery --available  "openssl*"   `
after if we do
`dnf --releasever=25 --disablerepo='*' --enablerepo=unitedrpms repoquery --available  "openssl*" `
give me the same results , because use the same dnf cache , even reply is very quick . 
if we do 
`dnf --disablerepo='*' --enablerepo=unitedrpms clean all`
and repeat 
`dnf --releasever=25 --disablerepo='*' --enablerepo=unitedrpms repoquery --available  "openssl*" `
I already got the correct results. 

@kuboosoft any suggestion  ?

**Comment by kuboosoft** [comment]
I am testing in virgins docker containers, and I'am not sure about it (the repository is working fine); we have a [metadata_expire=1d](https://github.com/UnitedRPMs/unitedrpms/blob/master/unitedrpms.repo) in our repositories, the cache is cleaned each day... Can you test "sudo dnf update --refresh -vvv" without sudo

```
su -c 'dnf update --refresh -vvv'
```
Rawhide has dnf "2.5.0" I am not sure about the changes in dnf, but I suggest you replace the variable
$releasever to **27** , in the repository . Because a similar issue exist with "repoquery --whatrequires x264-libs --source --verbose"
.
I found when a "signature could not be verified" it stops  the repoquerry... a bad mirror or out/day also...

**Comment by ondrejholy** [comment]
The result is still same with `su` :-(

I tried changing `$releasever` to `27` earlier, but without any success:
```
Cannot download 'https://raw.githubusercontent.com/UnitedRPMs/unitedrpms.github.io/master/mirrorlist_F27_x86_64.txt': repomd.xml GPG signature verification error: Bad GPG signature.
```

**Comment by kuboosoft** [comment]
The issue is out our hands, and is a problem with dnf, Generally I never use a "dnf update --refresh" only "dnf clean all && dnf -y update --verbose" but I will check and test and track the issue.

**Comment by ondrejholy** [comment]
Thanks for the reply! I've filed the following bug report for dnf:
https://bugzilla.redhat.com/show_bug.cgi?id=1456419

**Comment by ondrejholy** [comment]
Thanks for help! Patch for the key verification issue has been proposed, see the dnf bugreport... The issue mentioned by @sergiomb2 isn't relevant, but it is probably another bug in dnf...

**Comment by sergiomb2** [comment]
@ondrejholy , can we find out why cache doesn't work correctly with official unitedrpms.repo ? , how debug it ? and where is the problem ? 

Thanks,

**Comment by kuboosoft** [comment]
![1](https://i.imgur.com/FAvcubU.png)

**Comment by ondrejholy** [comment]
@sergiomb2 I suppose this is also dnf bug, please file a new bug report for it:
https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora&component=dnf

**Comment by sergiomb2** [comment]
@kuboosoft I didn't understand 
```
cd /etc/pki/rpm-gpg/
ln -s URPMS-GPG-PUBLICKEY-Fedora-24 URPMS-GPG-PUBLICKEY-Fedora-25
ln -s URPMS-GPG-PUBLICKEY-Fedora-24 URPMS-GPG-PUBLICKEY-Fedora-26


rm /var/cache/dnf/* -rf

dnf --releasever=24 --disablerepo='*' --enablerepo=unitedrpms repoquery --available "openssl*" 

openssl-freeworld-2:1.0.2k-5.fc24.x86_64
etc

dnf --releasever=25 --disablerepo='*' --enablerepo=unitedrpms repoquery --available "openssl*" -vvv

openssl-freeworld-2:1.0.2k-5.fc24.x86_64
etc

dnf --releasever=25 --disablerepo='*' --enablerepo=unitedrpms clean all
dnf --releasever=25 --disablerepo='*' --enablerepo=unitedrpms repoquery --available "openssl*" -vvv

openssl-freeworld-2:1.0.2k-5.fc25.x86_64
etc 
```

maybe is not a dnf problem but could someone help us to understand what is wrong 

Many thanks

**Comment by kuboosoft** [comment]
If our repository ask for URPMS-GPG-PUBLICKEY-Fedora-?? then we also needs provides other GPG key (renamed our original GPG). It is fool,  but dnf should make the change with the GPG keys ( is automatic!!!) it fail... it uses a old version and is persistent!! the problem isn't here...

**Comment by sergiomb2** [comment]
Hi, 
using unitedrpms.repo from https://github.com/UnitedRPMs/unitedrpms/blob/master/unitedrpms.repo
if I change from mirrorlist to baseurl [1] things start work correctly since also gitlab IIRC is to remove I propose update unitedrpms.repo to use baseurl

thanks

[1]
```
#mirrorlist=https://raw.githubusercontent.com/UnitedRPMs/unitedrpms.github.io/master/mirrorlist_F$releasever_x86_64.txt
baseurl=https://sourceforge.net/projects/unitedrpms/files/$releasever/$basearch/
```

**Comment by kuboosoft** [comment]
I am [syncing manually](https://travis-ci.org/UnitedRPMs/f27-mirrorsync) (restarting) the mirror with gitlab (each update), as I said you, it causes problems. I disabled "mirrorlist" in [mock-unitedrpms](https://github.com/UnitedRPMs/mock-unitedrpms), and in the unitedrpms repository of the docker containers...  we can discuss about russian mirror in private. The problems comes, when a mirror is unupdated...  I am no sure about the opinion of paul (with his mirror), but if we make the change; we must update [the rpm of unitedrpms repository](https://github.com/UnitedRPMs/unitedrpms) (The common way to install the unitedrpms repo)

**Comment by sergiomb2** [comment]
IMO , we should update and use : 

    baseurl=https://sourceforge.net/projects/unitedrpms/files/$releasever/$basearch/

in [the rpm of unitedrpms repository](https://github.com/UnitedRPMs/unitedrpms) 
apart of gitlab have problems or not, use the repolist is giving us problems.
IMO sf.net have already a bunch of mirrors and you will have less work , because you don't need update gitlab anymore , if Paul for some reason want keep gitlab synced and alive we may readd it again . 

Best regards,

**Comment by kuboosoft** [comment]
OK, then no problem :) Can you make the changes? I am testing a controversial package (sucessfully built)... can you login in  slack? I wrote you here ;)

**Comment by sergiomb2** [comment]
Done 
git push to github.com:UnitedRPMs/unitedrpms.git
   d29b5ca..b786ac2  master -> master

do yo do the release and update the README.md ? 

Thanks

**Comment by kuboosoft** [comment]
@sergiomb2 yes, I will sync today...

**Comment by aditiapratama** [comment]
I've got this issue this morning
`Failed to synchronize cache for repo 'unitedrpms', disabling.`

any workaround to solve it?

**Comment by aditiapratama** [comment]
ah it seems the problem are with sourceforge.net
![image](https://user-images.githubusercontent.com/982553/36183800-ac036934-1162-11e8-88b4-5769de383a22.png)

**Comment by kuboosoft** [comment]
@aditiapratama We only need wait.... "We are currently in maintenance mode while we bring our new datacenter online. Updates to follow."


https://twitter.com/sfnet_ops?lang=en
