### ISSUE TITLE
Update for nomacs

### ISSUE THREAD

**Issue by TheDcoder** [UnitedRPMs/issues#31]
The [nomacs](https://apps.fedoraproject.org/packages/nomacs) package in the official Fedora repository is very outdated and contains an ancient version (3.8)

Maybe it is a good idea to have an updated package for the [3.12](https://nomacs.org/nomacs-3-12/) version which has a lot of improvements in the UnitedRPMs repository? Sorry if this is out-of-scope but I thought it would be a cool addition! 😃

**Comment by kuboosoft** [comment]
If nomacs package in fedora is outdated, the best choice is open a [bugzilla report](https://bugzilla.redhat.com/)... I'm not sure if it's a massive package; but if it is correct, we can not update without breaking dependencies (bad).

**Comment by kuboosoft** [comment]
@TheDcoder If nomacs package in fedora is outdated, the best choice is open a [bugzilla report](https://bugzilla.redhat.com/)...

**Comment by TheDcoder** [comment]
@kuboosoft There are already 2 bugs open for updating the nomacs package ([1597451](https://bugzilla.redhat.com/show_bug.cgi?id=1597451) and [1689655](https://bugzilla.redhat.com/show_bug.cgi?id=1689655)), but no response to both of them :disappointed:

I think according to [Fedora Updates Prolicy](https://fedoraproject.org/wiki/Updates_Policy#Stable_Releases) maintainers are highly encouraged to not update software packages to the next major release for the current stable vesrion of the OS... and updates are long due, even the version in Fedora 30 is still 3.8

**Comment by kuboosoft** [comment]
@TheDecoder  ¿who maintains the package?....
 https://discussion.fedoraproject.org/t/workstation-working-group-call-for-participation/1544

**Comment by TheDcoder** [comment]
@kuboosoft Not sure, but the point of contact mentioned in fedora packages is [tieugene](https://fedoraproject.org/wiki/User:Tieugene), unfortunately the wikipage is empty and has no contact information.

**Comment by sergiomb2** [comment]
https://apps.fedoraproject.org/packages/nomacs/ on tab bug we already got bugs opened , you may add your comment there

**Comment by TheDcoder** [comment]
@sergiomb2 I have already mentioned them in one of my previous replies:

> There are already 2 bugs open for updating the nomacs package ([1597451](https://bugzilla.redhat.com/show_bug.cgi?id=1597451) and [1689655](https://bugzilla.redhat.com/show_bug.cgi?id=1689655)), but no response to both of them :disappointed:

I doubt the package maintainer is going respond as both of those tickets have been neglected. I am also not sure about the policy, so I am reluctant to comment on them.

I lack the skill and time to maintain a package myself, so I came up here to see if anyone was interested in adopting this software :smile:

**Comment by kuboosoft** [comment]
@TheDcoder Well; I am not sure if the [pull request](https://src.fedoraproject.org/rpms/nomacs/pull-request/2) of David Va ;) will be accepted; but he made some changes. I attach the rpms updated... Enjoy :)
[nomacs.zip](https://github.com/UnitedRPMs/issues/files/3118681/nomacs.zip)

**Comment by TheDcoder** [comment]
@kuboosoft Thanks for building the latest version! I hope the pull request gets accepted :)

Closing the bug/thread as seeing how there is at least someone trying to nomacs updated in the Fedora repository.

**Comment by sergiomb2** [comment]
> @TheDcoder Well; I am not sure if the [pull request](https://src.fedoraproject.org/rpms/nomacs/pull-request/2) of David Va ;) will be accepted; but he made some changes.

The commit is much better in organization but still can be better the commit [1]  may have be defined at least in 3 :

    - Added missing dependencies
    - Included internal plugins 
    - find_lang tricks 

[1] 
https://src.fedoraproject.org/fork/davidva/rpms/nomacs/c/7cdee9adaca7a56cb926dd2c4b872efc3b2a1af6

**Comment by kuboosoft** [comment]
Reason I love the changelog. The hand was given. Cost? A lemon tea :smile_cat:

**Comment by kuboosoft** [comment]
Yes but the changelog also is human readable. The hand was given. Cost? A lemon tea :smile_cat:

**Comment by TheDcoder** [comment]
Sorry about bumping this again, but I upgraded fedora today (to version 30) and it looks like the `libexiv2.so.26()(64bit)` dependency is unavaliable in the F30 repos...
```
Error: 
 Problem: conflicting requests
  - nothing provides libexiv2.so.26()(64bit) needed by nomacs-3.12-0.1.20190422git2ee2d8e.fc29.x86_64
```

@kuboosoft May I request you to rebuild the latest version for Fedora 30? Sorry about the trouble but I think it will be useful to have a build available for other Fedora users like me who aren't very experienced in building software 😅

**Comment by kuboosoft** [comment]
@TheDcoder is easy; I can help you to rebuild... but not maintaining it (also we need hands here). Imagine the release engineer in Fedora or other no accept a hand; then "pagure" shouldn't exist...

Solutions:
1) You can help us to maintain it here; we need hands. (you needs [learn basic tasks building rpms](https://docs.fedoraproject.org/en-US/quick-docs/creating-rpm-packages/)); our buildsystem builds && test the package; but you can test and [rebuild locally](https://github.com/UnitedRPMs/mock-unitedrpms) using our [mock](https://fedoraproject.org/wiki/Archive:Legacy/Mock?rd=Legacy/Mock).. I put the repository and you maintains it (updating.., changing release if is necessary a rebuild). Please read our [WIKI](https://github.com/UnitedRPMs/WIKI/wiki)

2) Make by your hand, a COPR with the package.

3) Make by your hand, a OBS with the package.

**Comment by TheDcoder** [comment]
@kuboosoft Thank you for the instructions and explanation, I do not think it is a good idea for me to maintain publicly usable software... I struggle packaging my own programs, safe to say that I am not fit for redistributing programs made by others 😅

I think the best option now is to bring attention to the outdated package in the Fedora repository, I am not sure how we can escalate the issue though.

**Comment by sergiomb2** [comment]
@kuboosoft  

https://src.fedoraproject.org/fork/sergiomb/rpms/nomacs/c/2b640804992009ef54dcd2a267836133aa00df5e?branch=master

https://copr.fedorainfracloud.org/coprs/sergiomb/opencv/package/nomacs/
but is failing on Fedora 30+ 
https://copr.fedorainfracloud.org/coprs/sergiomb/opencv/build/910319/

**Comment by kuboosoft** [comment]
@sergiomb2 only rawhide.... here the complete log... https://travis-ci.org/UnitedRPMs/nomacs

**Comment by kuboosoft** [comment]
@sergiomb2 I already patched it... and now it compile in [F31/rawhide](https://github.com/UnitedRPMs/nomacs/commit/00096e62cacfdd572aba4c9de69ae5329c2a5809) . xfeatures2d or static lib isn't necessary if you are using opencv of fedora... [results here](https://travis-ci.org/UnitedRPMs/nomacs/builds/534361972)  :smile_cat:
