### ISSUE TITLE
Urgent! URPMS users!! Our security keys expired

### ISSUE THREAD

**Issue by kuboosoft** [UnitedRPMs/issues#35]
"Dear URPMS users!! Urgent! Our security keys expired https://github.com/UnitedRPMs/issues/issues/34 ; then you need our new key; please install again our repository. Thanks for to love the project." 

https://unitedrpms.github.io/#repository

**Comment by sergiomb2** [comment]
Happy birthday UnitedRPMs !!! :sweat_smile:

**Comment by TheDcoder** [comment]
Glad to see that this issue has been fixed... Mozilla also did the same mistake with their addon signing key :wink:
