### ISSUE TITLE
mpv fails to build due to unpackaged files on Fedora 30

### ISSUE THREAD

**Issue by woolwood** [UnitedRPMs/issues#36]
Using `mpv.spec` from [mpv-0.29.1-8.gite9fae41.fc30.src.rpm](https://osdn.net/projects/unitedrpms/storage/30/srpm/mpv-0.29.1-8.gite9fae41.fc30.src.rpm):

> Installed (but unpackaged) file(s) found:
> /usr/share/man/man1/mpv.1.gz

In `mpv.spec`, I see under `%files`:

```
%if 0%{?fedora} <= 28
%{_mandir}/man1/mpv.1.gz
%endif
```
I believe this ought to be 
```
%if 0%{?fedora} >= 28
%{_mandir}/man1/mpv.1.gz
%endif
```
which fixes the build.

**Comment by kuboosoft** [comment]
@woolwood ; Hi;  I can't reproduce the issue... [Check the build test](https://api.travis-ci.org/v3/job/537672843/log.txt)

**Comment by woolwood** [comment]
Hm, are you sure the .spec you used to test the build contains
```
%{_datadir}/zsh/site-functions/_mpv
%if 0%{?fedora} <= 28
%{_mandir}/man1/mpv.1.gz
```
under %files?

**Comment by kuboosoft** [comment]
@woolwood check, the build test with the commit (The current commit has the fix for the issue https://github.com/UnitedRPMs/issues/issues/37)... How are you building your src.rpm? mock, only rpmbuild?
https://github.com/UnitedRPMs/mpv/tree/d343cf6d3f41b3fa47b83c78f906df1f1aa23adc

**Comment by woolwood** [comment]
Only rpmbuild. (rpmbuild -bp to patch and -bb to build).
The latest still fails to build

> Checking for unpackaged file(s): /usr/lib/rpm/check-files /home/adriaan/rpmbuild/BUILDROOT/mpv-0.29.1-9.gite9fae41.fc30.x86_64
> error: Installed (but unpackaged) file(s) found:
>    /usr/share/man/man1/mpv.1.gz
> 
> 
> RPM build errors:
>     Installed (but unpackaged) file(s) found:
>    /usr/share/man/man1/mpv.1.gz
> 

This is because of 
```
%if 0%{?fedora} <= 28
%{_mandir}/man1/mpv.1.gz
%endif
``` 
in `%files`. I'm running Fedora 30, so not lesser or equal than 28, and so %{_mandir}/man1/mpv.1.gz doesn't get packaged and the rpmbuild fails. Adjusting <= to >= fixes the build.
