### ISSUE TITLE
mpv reports unknown version

### ISSUE THREAD

**Issue by woolwood** [UnitedRPMs/issues#37]
This one's minor.

> [cplayer] mpv 0.29.0-UNKNOWN Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
> [cplayer]  built on UNKNOWN

I understand "built on UNKNOWN", it's due to `--disable-build-date` in `mpv_options`. But "0.29.0-UNKNOWN" seems to be a bug.

**Comment by kuboosoft** [comment]
@woolwood it is design of code; check the [source code](https://github.com/mpv-player/mpv/blob/master/common/version.c#L22)... 

[Here our fix](https://github.com/UnitedRPMs/mpv/commit/3c3f95048d276efa71de65dd2eeae0f33c5c9ecd)...

**Comment by woolwood** [comment]
This changes the builddate to UnitedRPMs, but doesn't change the version:

> mpv 0.29.0-UNKNOWN Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
>  built on UnitedRPMs

I was talking about the "0.29.0-UNKNOWN" part. I feel like it should be {version}-%gver? So e.g.:
mpv 0.29.1-gite9fae41 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects

**Comment by woolwood** [comment]
Putting `sed -i 's|0.29.0-UNKNOWN|%{version}-git%shortcommit0|g' $PWD/%{name}/VERSION` in `mpv.spec` works. But of course this is very minor and maybe more of a preference than a bug—it just seems to make sense to print the actual version rather than the default outdated/imprecise one in VERSION.
With this, mpv --version returns

> mpv 0.29.1-gite9fae41 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects

**Comment by kuboosoft** [comment]
@woolwood can you make a pull request? Your hand is welcome... :smiley:

**Comment by kuboosoft** [comment]
Done, enjoy!
