### ISSUE TITLE
tribler-7.2.2-1.fc30.noarch won't install looking or python2-libnacl

### ISSUE THREAD

**Issue by jalbstmeijer** [UnitedRPMs/issues#39]
```
#dnf install tribler
Last metadata expiration check: 0:05:18 ago on Mon 03 Jun 2019 04:59:10 PM CEST.
Error: 
 Problem: conflicting requests
  - nothing provides python2-libnacl needed by tribler-7.2.2-1.fc30.noarch
(try to add '--skip-broken' to skip uninstallable packages)

```
Looking in the repo, it seems there is a src package python2-libnacl-1.6.1-7.fc30.src-37f085c5d538.rpm instead of a binary rpm.

https://sourceforge.net/projects/unitedrpms/files/30/x86_64/

**Comment by kuboosoft** [comment]
@jalbstmeijer tribler will be die (if the developer does't take a action); the package depend of python2 and [Fedora is droping python2](https://fedoraproject.org/wiki/FinalizingFedoraSwitchtoPython3) (officially without support coming soon) [feature reported here](https://github.com/Tribler/tribler/issues/3883). We have problems with tons of python modules deleted in F30 (is a serious problem maintains a package working yet with python2)...  At this moment the package is frozen.
