### ISSUE TITLE
[fdk-aac-freeworld] Error while loading shared libraries

### ISSUE THREAD

**Issue by Kcchouette** [UnitedRPMs/issues#40]
Related to https://bugzilla.rpmfusion.org/show_bug.cgi?id=5298

Hello

I have this message:

 $ error while loading shared libraries: libfdk-aac.so.2: cannot open shared object file: No such file or directory

In /usr/lib64/fdk-aac-freeworld

total 2304
drwxr-xr-x.   2 root root    4096 Jun 27 23:29 .
dr-xr-xr-x. 258 root root  258048 Jun 27 23:29 ..
lrwxrwxrwx.   1 root root      19 Jun 25 00:50 libfdk-aac.so.2 -> libfdk-aac.so.2.0.0
-rwxr-xr-x.   1 root root 2091536 Jun 25 00:50 libfdk-aac.so.2.0.0

Package fdk-aac-2.0.0-4.fc30.x86_64.rpm

**Comment by Kcchouette** [comment]
Related to https://github.com/UnitedRPMs/fdk-aac/commit/50aa043c1e5d77bda8b680ec7476310972b0aa7d

**Comment by kuboosoft** [comment]
@Kcchouette Hi, reading bug reports from a fragmented and forgot repository (Surely someone in RF needs their medicines for diarrhea); the solution is simple... :smile_cat: 

`dnf clean all && dnf -y update`
`dnf -y install fdk-aac-free`

Please avoid mixing UnitedRPMs with Rpmfusion/others...

results...

```
[makerpm@localhost ~]$ rpm -q fdk-aac
fdk-aac-2.0.0-4.fc30.x86_64
[makerpm@localhost ~]$ rpm -q fdk-aac-free
fdk-aac-free-0.1.6-3.fc30.x86_64
[makerpm@localhost ~]$ 
```

https://github.com/UnitedRPMs/issues/issues/41
