### ISSUE TITLE
can't install handbrake

### ISSUE THREAD

**Issue by feurry** [UnitedRPMs/issues#42]
sudo dnf install handbrake-gui
Last metadata expiration check: 0:16:12 ago on Tue 16 Jul 2019 08:48:04 PM EDT.
Error: 
 Problem: conflicting requests
  - nothing provides libx265.so.169()(64bit) needed by handbrake-gui-1.2.2-8.git4eb9f7b.fc30.x86_64
(try to add '--skip-broken' to skip uninstallable packages)

I just upgraded to fedora 30 and tried to install Handbrake and I think x265 was updated and handbrake is looking for the old files.

x265 is now 3.1.1-7
https://unitedrpms.sourceforge.io/x86_64/repoview/x265.html

**Comment by kuboosoft** [comment]
@feurry Thanks for the report; the issue will be solved in the nexts hours.

**Comment by feurry** [comment]
Thanks so much! Everything works
