### ISSUE TITLE
[Fedrora 32 beta] can`t install handbrake

### ISSUE THREAD

**Issue by bhaubeck** [UnitedRPMs/issues#45]
dnf install handbrake-gui                                                                                                                   /home/ben
Last metadata expiration check: 0:07:53 ago on Wed 18 Mar 2020 02:04:39 PM CET.
Error: 
 Problem: conflicting requests
  - nothing provides libx265.so.179()(64bit) needed by handbrake-gui-1.3.1-7.fc32.x86_64
(try to add '--skip-broken' to skip uninstallable packages)

**Comment by kuboosoft** [comment]
Hi. Thanks for the report. Please update.

`dnf clean all && dnf -y update`

**Comment by bhaubeck** [comment]
great, works!
thanks!
