### ISSUE TITLE
VAAPI video encoding problem

### ISSUE THREAD

**Issue by devrootware** [UnitedRPMs/issues#47]
Hi guys. I use Fedora 32 and install chromium-freeworld from your repository and thank you for job, but have a problem online video streams are they dont work correctly. See screenshot. 

But if i use stock chromium with vaapi it's work normal 

Can u help fix it?

Debug information are present in screenshots.

**Comment by kuboosoft** [comment]
@devrootware Thanks for the report. Can you share a capture with 

`chrome://gpu/`

Also all about your graphic card.

**Comment by devrootware** [comment]
Intel UHD 600 built in celeron n4000.

![Снимок экрана от 2020-03-29 18-36-41](https://user-images.githubusercontent.com/62841555/77853328-4ad64b80-71ec-11ea-9ca6-a58062884d79.png)
![Снимок экрана от 2020-03-29 18-35-54](https://user-images.githubusercontent.com/62841555/77853329-4c077880-71ec-11ea-837c-5d882a3d43bb.png)
![Снимок экрана от 2020-03-29 18-35-52](https://user-images.githubusercontent.com/62841555/77853330-4ca00f00-71ec-11ea-8718-8c191180810a.png)
![Снимок экрана от 2020-03-29 18-35-50](https://user-images.githubusercontent.com/62841555/77853332-4d38a580-71ec-11ea-80b8-013a0f42a25f.png)
![Снимок экрана от 2020-03-29 18-35-48](https://user-images.githubusercontent.com/62841555/77853333-4d38a580-71ec-11ea-834c-180810ce3f44.png)
![Снимок экрана от 2020-03-29 18-35-47](https://user-images.githubusercontent.com/62841555/77853334-4dd13c00-71ec-11ea-9277-85bd04aa7421.png)
![Снимок экрана от 2020-03-29 18-35-45](https://user-images.githubusercontent.com/62841555/77853335-4e69d280-71ec-11ea-902f-3d711a89b15e.png)
![Снимок экрана от 2020-03-29 18-35-44](https://user-images.githubusercontent.com/62841555/77853336-4f026900-71ec-11ea-8d80-3af68a069154.png)
![Снимок экрана от 2020-03-29 18-35-41](https://user-images.githubusercontent.com/62841555/77853337-4f026900-71ec-11ea-899f-4743d3599f08.png)

I

**Comment by kuboosoft** [comment]
@devrootware Ok, enable it:

`chrome://flags/#enable-oop-rasterization`

**Comment by devrootware** [comment]
@devrootware no changes. have pink colored video on youtube.

**Comment by devrootware** [comment]
Can fix it manually by this tip xD
https://copr.fedorainfracloud.org/coprs/che/mesa/
echo "allow_rgb10_configs=false" >> /etc/environment
I think this expiricence may help other :)
Video stay normal. Thx for your awesome project, best regards.
