### ISSUE TITLE
jitsi-2.11.5633-1.fc32.x86_64 no video

### ISSUE THREAD

**Issue by tiomadrid** [UnitedRPMs/issues#53]
jjitsi-2.11.5633-1.fc32.x86_64 no video

jitsi-2.10-5550.x86_64 has working video on the same system

5.6.15-300.fc32.x86_64

**Comment by kuboosoft** [comment]
@tiomadrid Thanks for the report. The issue is already solved. 

```
su
dnf clean all && dnf -y update
```

**Comment by tiomadrid** [comment]
Thanks, done that.
jitsi-2.11.5633-2.fc32.src.rpm has video in settings only when checking webcam.
During videocall host webcam switches on and only sound of remote party can be heard by host.
Host does not receive remote party's video, only receives sound.
Remote party does not receive host's sound and video.
Text chat works OK.
OTR has disappeared after upgrade to above version of jitsi, is not listed as option in text chat.
Presence works OK.

**Comment by tiomadrid** [comment]
[jitsi_debug_log.txt](https://github.com/UnitedRPMs/issues/files/4851436/jitsi_debug_log.txt)

Jitsi debug log

**Comment by tiomadrid** [comment]
Upgraded to fc33.x86_64
