### ISSUE TITLE
Audacity, some plugins do not work

### ISSUE THREAD

**Issue by ValdikSS** [UnitedRPMs/issues#54]
It seems that Audacity autotools build script is broken and causes issues with the plugins. Audacity team recommends to compile it with cmake.
Other distros had the same issue: https://forum.audacityteam.org/viewtopic.php?f=48&t=111500, https://forum.audacityteam.org/viewtopic.php?f=48&t=111357

**Comment by kuboosoft** [comment]
@ValdikSS  thanks for the report; the update will be available in the next hours. :smiley_cat:

**Comment by ValdikSS** [comment]
Works fine, thanks!
