### ISSUE TITLE
Opera browser does not receive update

### ISSUE THREAD

**Issue by jospol2** [UnitedRPMs/issues#56]
Hi. Opera browser, has not moved from this version for a long time: opera-69.0.3686.57-3.fc32.x86_64.rpm, when it is currently in this version: 70.0.3728.133.

Do you know why this happens?

Thanks for everything.

Regards.

Excuse my clumsiness, I mean the Fedora distribution:

https://fedora.pkgs.org/32/unitedrpms-x86_64/opera-69.0.3686.57-3.fc32.x86_64.rpm.html

As you can see, the package has been frozen for a long time.

**Comment by kuboosoft** [comment]
@jospol2 Thanks for the report; the update will be synced in the next hours. 12 hours max. :v:

**Comment by jospol2** [comment]
Thanks to you for the great work you do. I have seen that it is already updated. Regards
 
 
  El mar., sept. 1, 2020 a 5:08, kuboosoft<notifications@github.com> escribió:   


@jospol2 Thanks for the report; the update will be synced in the next hours. 12 hours max. ✌️
