### ISSUE TITLE
obs-studio doesn't have 27.0.0 but you released packages with this version

### ISSUE THREAD

**Issue by yurivict** [UnitedRPMs/issues#58]
See here https://repology.org/project/obs-studio/versions how your RPMs are the only ones of version 27.0.0.

27.0.0-rc2 is the last RC that obs-studio tagged: https://github.com/obsproject/obs-studio/tags

**Comment by kuboosoft** [comment]
@yurivict Hi. And what is the problem? [Release Candidate](https://www.pcmag.com/encyclopedia/term/release-candidate#:~:text=A%20release%20candidate%20is%20like,the%20final%20release%20of%20software.); UnitedRPMs isn't the unique who made a rpm with a RC (openmandriva...) It is a fact that you are using the stable version ... There are a few days left for a final release. In no way am I going to reverse this, our users need to test the wayland support and report any bugs to obs-studio.

**Comment by yurivict** [comment]
Because there is no 27.0.0 - only 27.0.0-RC2. You didn't assign the correct version.

**Comment by kuboosoft** [comment]
@yurivict I can't put Non-numeric in "version tag" (call it avoid issues in the next update), if you know about packaging you know it... if not I recommend read it. 
https://fedoraproject.org/wiki/PackagingDrafts/TildeVersioning#Pre-Release_Packages

**Comment by yurivict** [comment]
> I can't put Non-numeric in "version tag" (call it avoid issues in the next update), if you know about packaging you know it... if not I recommend read it.

Of course you can put non-numerics into a package version: https://repology.org/project/gretl/versions
