### ISSUE TITLE
jitsi-2.11.5633-2.fc33 SIP video call not working. Sometimes SIP audio call not working.

### ISSUE THREAD

**Issue by tiomadrid** [UnitedRPMs/issues#59]
Name         : jitsi
Version      : 2.11.5633
Release      : 2.fc33
Architecture : x86_64
5.12.7-200.fc33.x86_64

SIP video call not working. Sometimes SIP audio call not working.
[jitsi_debug2.txt](https://github.com/UnitedRPMs/issues/files/6566433/jitsi_debug2.txt)

**Comment by kuboosoft** [comment]
@tiomadrid unfortunately the java version uses an old version of ffmpeg; there are no correcting changes to the project. Luckily exist a official development version using "electron" with a more modern and usable interface. You can install "[jitsi-meet-electron](https://github.com/UnitedRPMs/jitsi-meet-electron)"

**Comment by tiomadrid** [comment]
@kuboosoft for me it was not clear what you meant by the java version, I have three java versions to choose from and tried all in vain. So the java version refers to Jitsi desktop and that will not be fixed. I am interested in a desktop version for SIP calls. Thanks for pointing me to https://github.com/UnitedRPMs/jitsi-meet-electron. What is the difference to https://github.com/jitsi/jitsi-meet-electron? Why would I want to install that? Is that a desktop app for SIP calls? Many thanks.

**Comment by kuboosoft** [comment]
@tiomadrid Is only a modern alternative... The best review is the one you can do; doing the tests, and if it suits your needs. I use the the electron version with my students. If it does not adapt, you can eliminate it.  https://github.com/jitsi/jitsi-meet-electron

**Comment by tiomadrid** [comment]
@kuboosoft Thank you. I posted this [https://community.jitsi.org/t/jitsi-2-11-5633-sip-video-call-not-working-sometimes-sip-audio-call-not-working/101189?u=tio_madrid](url) . Maybe someone can help.

**Comment by tiomadrid** [comment]
@kuboosoft  How to solve this?
Problem : package jitsi-2.11.5633-2.fc33.x86_64 requires ffmpeg3-libs, but none of the providers can be installed
  - package ffmpeg3-libs-3.4.2-18.fc33.x86_64 requires libx265.so.192()(64bit), but none of the providers can be installed
  - cannot install both x265-libs-3.5-7.fc33.x86_64 and x265-libs-3.4-7.fc33.x86_64
  - cannot install both x265-libs-3.4-3.fc33.x86_64 and x265-libs-3.5-7.fc33.x86_64
  - cannot install the best update candidate for package x265-libs-3.4-7.fc33.x86_64
  - cannot install the best update candidate for package jitsi-2.11.5633-2.fc33.x86_64

**Comment by tiomadrid** [comment]
@kuboosoft   How to solve this? 
[Problem.txt](https://github.com/UnitedRPMs/issues/files/6834331/Problem.txt)

**Comment by tiomadrid** [comment]
@kuboosoft Would this be of interest or helpful?
https://github.com/jitsi/jitsi/issues/738

Would you know how to compile Jitsi with the correct Java version that solves the issue?

There was a hint here which did not work for me:
[Jitsi community](https://community.jitsi.org/t/jitsi-2-11-5633-sip-video-call-not-working-sometimes-sip-audio-call-not-working/101189?u=tio_madrid)

**Comment by sergiomb2** [comment]
I already commit the fix https://github.com/UnitedRPMs/jitsi/commits/master

**Comment by tiomadrid** [comment]
@sergiomb2 Thank you. Does that only work with Fedora 34 because it is build on "F34+"?
My version is still 33 and I see below  update problems which cannot be resolved? Would those be related to packages provided by UnitedRPMs and how to fix this?

Problem 1: gstreamer1-1.18.2-7.git6a62351.fc33.i686 has inferior architecture
  - cannot install both gstreamer1-1.19.1-7.git6fa03dd.fc33.x86_64 and gstreamer1-1.18.2-7.git6a62351.fc33.x86_64
  - cannot install the best update candidate for package gstreamer1-1.18.2-7.git6a62351.fc33.i686
  - cannot install the best update candidate for package gstreamer1-1.18.2-7.git6a62351.fc33.x86_64
 Problem 2: gstreamer1-plugins-base-1.18.2-1.fc33.i686 has inferior architecture
  - cannot install both gstreamer1-plugins-base-1.19.1-7.fc33.x86_64 and gstreamer1-plugins-base-1.18.2-1.fc33.x86_64
  - cannot install both gstreamer1-plugins-base-1.18.2-1.fc33.x86_64 and gstreamer1-plugins-base-1.19.1-7.fc33.x86_64
  - cannot install the best update candidate for package gstreamer1-plugins-base-1.18.2-1.fc33.i686
  - cannot install the best update candidate for package gstreamer1-plugins-base-1.18.2-1.fc33.x86_64
 Problem 3: cannot install both x264-libs-1:0.161-7.gitd198931.fc33.x86_64 and x264-libs-1:0.159-7.git296494a.fc33.x86_64
  - package ffmpeg3-libs-3.4.2-18.fc33.x86_64 requires libx264.so.159()(64bit), but none of the providers can be installed
  - cannot install the best update candidate for package x264-libs-1:0.159-7.git296494a.fc33.x86_64
  - cannot install the best update candidate for package ffmpeg3-libs-3.4.2-18.fc33.x86_64
 Problem 4: package jitsi-2.11.5633-2.fc33.x86_64 requires ffmpeg3-libs, but none of the providers can be installed
  - package ffmpeg3-libs-3.4.2-18.fc33.x86_64 requires libx265.so.192()(64bit), but none of the providers can be installed
  - cannot install both x265-libs-3.5-7.fc33.x86_64 and x265-libs-3.4-7.fc33.x86_64
  - cannot install both x265-libs-3.4-3.fc33.x86_64 and x265-libs-3.5-7.fc33.x86_64
  - cannot install the best update candidate for package x265-libs-3.4-7.fc33.x86_64
  - cannot install the best update candidate for package jitsi-2.11.5633-2.fc33.x86_64
 Problem 5: problem with installed package ffmpeg3-libs-3.4.2-18.fc33.x86_64
  - package ffmpeg3-libs-3.4.2-18.fc33.x86_64 requires libx264.so.159()(64bit), but none of the providers can be installed
  - cannot install both x264-libs-1:0.161-7.gitd198931.fc33.x86_64 and x264-libs-1:0.159-7.git296494a.fc33.x86_64
  - package ffmpeg-libs-4.4-7.fc33.x86_64 requires libx264.so.161()(64bit), but none of the providers can be installed
  - cannot install the best update candidate for package ffmpeg-libs-4.3.1-12.fc33.x86_64
 Problem 6: problem with installed package jitsi-2.11.5633-2.fc33.x86_64
  - package jitsi-2.11.5633-2.fc33.x86_64 requires ffmpeg3-libs, but none of the providers can be installed
  - package ffmpeg3-libs-3.4.2-18.fc33.x86_64 requires libx265.so.192()(64bit), but none of the providers can be installed
  - cannot install both x265-libs-3.5-7.fc33.x86_64 and x265-libs-3.4-7.fc33.x86_64
  - cannot install both x265-libs-3.4-3.fc33.x86_64 and x265-libs-3.5-7.fc33.x86_64
  - package gstreamer1-plugins-bad-freeworld-1.19.1-7.fc33.x86_64 requires libx265.so.199()(64bit), but none of the providers can be installed
  - cannot install the best update candidate for package gstreamer1-plugins-bad-freeworld-1.18.4-7.fc33.x86_64

**Comment by kuboosoft** [comment]
@tiomadrid Don't worry the update coming in the next hours.

**Comment by tiomadrid** [comment]
Thank you, the update went trough OK. Attached a debug log.
[jitsi_debug_20210726.txt](https://github.com/UnitedRPMs/issues/files/6880530/jitsi_debug_20210726.txt)

**Comment by tiomadrid** [comment]
openjdk version "1.8.0_302"
OpenJDK Runtime Environment (build 1.8.0_302-b08)
OpenJDK 64-Bit Server VM (build 25.302-b08, mixed mode)

Tested XMPP call and video call and SIP call and video call.
[jitsi_debug_20210801.txt](https://github.com/UnitedRPMs/issues/files/6912934/jitsi_debug_20210801.txt)

**Comment by tiomadrid** [comment]
[Jitsi Desktop community comment by gpatel-fr](https://community.jitsi.org/t/jitsi-2-11-5633-sip-video-call-not-working-sometimes-sip-audio-call-not-working/101189/7)

**Comment by tiomadrid** [comment]
@kuboosoft Did you have a chance to look at both debug files? Do you know what causes the errors?

**Comment by kuboosoft** [comment]
@tiomadrid 
`You seem to use a 64 bits Java and the native libraries for Jitsi are built for 32 bits` Badly I can't run it; also  built in 32 bits; I am not using Fedora 33 for test it. I am using Fedora 34 and Rawhide. Patches are welcome. I can only recommend the electron alternative. The package will be removed if it is not working properly.

**Comment by tiomadrid** [comment]
@kuboosoft What is required to solve this? Upgrade to Fedora 34 and then? How do I install the necessary 32 bit Java version? Can Jitsi be configured to run with 32 bit Java while everything else uses the system wide configured 64 bit Java version? Can Jitsi be build for 64 bit Java and you cannot do that and this is what you mean by patches are welcome? Would an appimage be a solution to solve this configuration puzzle?

**Comment by tiomadrid** [comment]
@sergiomb2 @kuboosoft Please view this comment.
https://community.jitsi.org/t/jitsi-2-11-5633-sip-video-call-not-working-sometimes-sip-audio-call-not-working/101189/11

**Comment by sergiomb2** [comment]
> @sergiomb2 @kuboosoft Please view this comment.
> https://community.jitsi.org/t/jitsi-2-11-5633-sip-video-call-not-working-sometimes-sip-audio-call-not-working/101189/11

it is an easy fix https://github.com/UnitedRPMs/jitsi/blob/master/jitsi.spec#L59 instead  find lib/native/linux$(sed 's/_/-/g' <<<${CARCH/#*(i?86|x86)/})/ -maxdepth 1 -type f -execdir install -Dm644 {} "%{buildroot}/%{_libdir}/%{name}/lib/native/"{} \; 

should be native/linux-64

**Comment by sergiomb2** [comment]
ENOTIME but I will check mageia package oneday

**Comment by tiomadrid** [comment]
@sergiomb2 Have you seen the two ant logs? There are deprecation, org.osgi.framework.BundleException, missing requirement. Is that related to my Java setup or to the Jitsi git clone with any of the included files like build.xml?
[ant rebuild.txt](https://github.com/UnitedRPMs/issues/files/6971624/ant.rebuild.txt)
[ant rebuild run.txt](https://github.com/UnitedRPMs/issues/files/6971627/ant.rebuild.run.txt)

**Comment by sergiomb2** [comment]
it builds fine on F34 when we set java home to jdk8 

`export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk`

**Comment by sergiomb2** [comment]
huf last commit breaks things [1] , I remove last commit, and fix other things in https://github.com/UnitedRPMs/jitsi/commit/cea7f17eb6664eaf5a835e5d98169bdc96894eb8

https://github.com/jitsi/jitsi/pull/731#issuecomment-898058986

**Comment by tiomadrid** [comment]
@sergiomb2 
> it builds fine on F34 when we set java home to jdk8
> 
> `export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk`

Meanwhile I have upgraded to Fedora 34 and installed java-1.8.0-openjdk-1.8.0.302.b08-0.fc34.x86_64

$ sudo update-alternatives --config java
openjdk version "1.8.0_302"
OpenJDK Runtime Environment (build 1.8.0_302-b08)
OpenJDK 64-Bit Server VM (build 25.302-b08, mixed mode)

$ sudo update-alternatives --config javac
javac 1.8.0_302

$ ant -version
Apache Ant(TM) version 1.10.9 compiled on January 12 1970

I struggle with the configuration.

Do I still need to set $JAVA_HOME? What if I switch from Java 8 to 11, would I need to amend $JAVA_HOME again?
Do I need to set $ANT_HOME or put anything in ~/.antrc?

I tried setting $JAVA_HOME in ~/.bash_profile, did source ~/.bash_profile, and am unsure how to do that right because each time the build fails and there is this message
[javac] warning: [options] bootstrap class path not set in conjunction with -source 8

I tried this too which seems to point to JRE
export JAVA_HOME=$(readlink -f /usr/bin/java | sed "s:/bin/java::")

Where and how to set $JAVA_HOME so that it fits into this system with Java 8 and 11 when I switch versions with update-alternatives --config?

**Comment by kuboosoft** [comment]
@tiomadrid Well it works again. Please update to jitsi "2.11.5633-5"; Can we close it?

**Comment by tiomadrid** [comment]
@kuboosoft
Does not work for me.
Cannot make or receive SIP video call.
Cannot make or receive XMPP call and video call. 

Also, XMPP specific: 
Call ended by remote side.
Reason: Failed application
Error: Could not establish connection (ICE failed and no relay found)

Log:
[jitsi_debug_2021-08-23.txt](https://github.com/UnitedRPMs/issues/files/7034690/jitsi_debug_2021-08-23.txt)

**Comment by sergiomb2** [comment]
org.freedesktop.dbus.exceptions.DBusException: Failed to connect to bus Failed to auth , is your dbus , please reboot 
or launch jitsi with your user session

**Comment by kuboosoft** [comment]
Also remove "$HOME/.jitsi"

**Comment by tiomadrid** [comment]
@kuboosoft  I have relaunched, still the same.
@kuboosoft "Also remove "$HOME/.jitsi""  What do you mean by that? The package was installed with dnf from your repository. Why is that necessary in my case and would that be necessary for anyone else, too?

**Comment by tiomadrid** [comment]
@sergiomb2 Rebooted.
@kuboosoft Removed "$HOME/.jitsi".
[jitsi_debug_2021-08-24.txt](https://github.com/UnitedRPMs/issues/files/7040756/jitsi_debug_2021-08-24.txt)

**Comment by tiomadrid** [comment]
[Update problems.txt](https://github.com/UnitedRPMs/issues/files/7040970/Update.problems.txt)

**Comment by sergiomb2** [comment]
> org.freedesktop.dbus.exceptions.DBusException: Failed to connect to bus Failed to auth , is your dbus , please reboot
> or launch jitsi with your user session

I checked my jitsi package and I have the same problem . but does star , I tested camera preview and doesn't work , it it time to give up , it is very old ask for google talk credentials ...

**Comment by kuboosoft** [comment]
@tiomadrid Because you are using a "gstreamer1-plugins-ugly-1:1.18.4-2" with a "[epoch](http://novosial.org/rpm/epoch/index.html) version" and from [other Third-party repository](https://github.com/negativo17/gstreamer1-plugins-bad/blob/master/gstreamer1-plugins-bad.spec#L8)... Our current version in F33-F35 (gstreamer1-plugins-ugly-1.19.1-8). Please read here. The problem isn't here... https://github.com/UnitedRPMs/WIKI/wiki

**Comment by kuboosoft** [comment]
> > org.freedesktop.dbus.exceptions.DBusException: Failed to connect to bus Failed to auth , is your dbus , please reboot
> > or launch jitsi with your user session
> 
> I checked my jitsi package and I have the same problem . but does star , I tested camera preview and doesn't work , it it time to give up , it is very old ask for google talk credentials ...

Install **ffmpeg3-libs**  
https://github.com/UnitedRPMs/jitsi/commit/cea7f17eb6664eaf5a835e5d98169bdc96894eb8#diff-c2f21692e73dc29a0fb2c8bc5165a269152ad4ef66524a325bb529a37f0f017eL34  :wink:

**Comment by tiomadrid** [comment]
@kuboosoft 
> Install ffmpeg3-libs

Installed OK. Camera preview works.

[jitsi_debug_20210827.txt](https://github.com/UnitedRPMs/issues/files/7069130/jitsi_debug_20210827.txt)

**Comment by kuboosoft** [comment]
@tiomadrid I am not sure if XMPP works; but  google talk does not work anymore... Test the SIP.

**Comment by Neustradamus** [comment]
To follow this ticket.

**Comment by tiomadrid** [comment]
[jitsi_debug_20210901.txt](https://github.com/UnitedRPMs/issues/files/7093841/jitsi_debug_20210901.txt)

**Comment by tiomadrid** [comment]
Upgraded to Fedora 36.
