### ISSUE TITLE
Shotcut 21.05.18 crashes on import of videos

### ISSUE THREAD

**Issue by tiomadrid** [UnitedRPMs/issues#60]
Shotcut 21.05.18 crashes on import of videos

Name         : shotcut
Version      : 21.05.18
Release      : 7.fc33
Architecture : x86_64
Size         : 12 M
Source       : shotcut-21.05.18-7.fc33.src.rpm
From repo    : unitedrpms

**Comment by kuboosoft** [comment]
@tiomadrid can you share your RAM info? and paste here the results opening shotcut in a terminal?

**Comment by tiomadrid** [comment]
@kuboosoft  Shotcut fails to import video files and crashes when creating a new project > enter project name > start.
[shotcut_debug.txt](https://github.com/UnitedRPMs/issues/files/6689052/shotcut_debug.txt)

**Comment by kuboosoft** [comment]
@tiomadrid Low memory Ram... for some reason, blocks import files with low memory (the log show you have 3.683032 GB).

**Comment by tiomadrid** [comment]
@kuboosoft  Same machine and file, different version=shotcut-linux-x86_64-210615.AppImage. No crash.
[shotcut_debug3.txt](https://github.com/UnitedRPMs/issues/files/6796883/shotcut_debug3.txt)

Shotcut 21.05.18 crashes at creating a new project.

**Comment by kuboosoft** [comment]
@tiomadrid don't worry; maybe we need revert the update. I need test some things. Shotcut uses the new mlt 7 (unstable yet).
