### ISSUE TITLE
jitsi-2.11.5633-5.fc35 no video on Fedora 36

### ISSUE THREAD

**Issue by tiomadrid** [UnitedRPMs/issues#62]
jitsi-2.11.5633-5.fc35 no video on Fedora 36

Linux fedora 5.17.6-300.fc36.x86_64

Name         : jitsi
Version      : 2.11.5633
Release      : 5.fc35
Architecture : x86_64

Name         : ffmpeg4-libs
Version      : 4.4.1
Release      : 4.fc36
Architecture : x86_64

**Comment by tiomadrid** [comment]
[Jitsi_debug_2022-05-15.txt](https://github.com/UnitedRPMs/issues/files/8695061/Jitsi_debug_2022-05-15.txt)

**Comment by kuboosoft** [comment]
@tiomadrid test the update, ffmpeg3 is already built. :)

**Comment by tiomadrid** [comment]
Works for me.
