### ISSUE TITLE
https://unitedrpms.github.io/#repository install rpm on Fedora 36

### ISSUE THREAD

**Issue by tiomadrid** [UnitedRPMs/issues#63]
https://unitedrpms.github.io/#repository
Install rpm on Fedora 36 not working this way:
sudo dnf -y install https://github.com/UnitedRPMs/unitedrpms/releases/download/19/unitedrpms-$(rpm -E %fedora)-19.fc$(rpm -E %fedora).noarch.rpm

Should 19 be 20?

Solution for me was https://sourceforge.net/projects/unitedrpms/files/36/x86_64/unitedrpms-36-20.fc36.noarch.rpm/download

**Comment by kuboosoft** [comment]
Hi, don't worry. We are synchronizing yet some packages.  But the repository is working now.
