### ISSUE TITLE
Disowning/Unmaintain Packages part I, II, III and IV

### ISSUE THREAD

**Issue by kuboosoft** [UnitedRPMs/issues#7]
We will [unmaintain](https://github.com/UnitedRPMs/WIKI/wiki/Maintaining-packages):

- VirtualBox
- VirtualBox-kmod
- mythtv
- mythplugins
- mpg123
- syncthing
- syncthing-inotify
- libreoffice-gtk3
- apm

----
PART II
- lame
- libmng
- zvbi
- dtksettings (only available in F28 oficially)
- deepin-tool-kit (coming soon to official)
- vid.stab (Now in official)
- foobnix (WebKit3 dropped)
- easy-ebook-viewer (WebKit3 dropped)
- [fdk-aac](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/F64JBJI2IZFT2A5QDXGHNMPALCQIVJAX/) (coming soon to official f27, but we need check the stripped version by Taymans; if it doesn't work us, then we need provides a "fdk-aac-freeworld")

----
PART III

- flameshot (Now in fedora repository)
- deepin-music
- twolame (Now in fedora repository)
- transmission-sequential
- libmpeg2 (Coming soon)
- rclone (Now in fedora repository)

PART IV
- dav1d (Now in fedora repository)

Reasons? None maintainers want to maintain or isn't necessary maintain; Some of these programs require a lot of time. [Any objections](https://github.com/UnitedRPMs/WIKI/wiki/Maintaining-packages)? Welcome but with a real solution.

**Comment by sergiomb2** [comment]
No , none at all , you may remove it please  , BTW I going integrate some patches about 3D acceleration passthrough on VBox of RF, made by Hans [1] https://fedoraproject.org/wiki/Changes/VirtualBox_Guest_Integration

**Comment by kuboosoft** [comment]
Ok, then the next sync, I will delete the packages in list ; also the final update for F24...

A bugzilla report for mpg123 was opened, the package is old; and we need a new, and drop our version...
https://bugzilla.redhat.com/show_bug.cgi?id=1480322
also a pull request...
https://src.fedoraproject.org/rpms/mpg123/pull-request/1

@sergiomb2 @fdelapena  @paulcarroty

**Comment by sergiomb2** [comment]
for me you may processed and delete the packages mentioned

**Comment by kuboosoft** [comment]
@sergiomb2 only vid.stab, dtksettings, deepin-tool-kit and fdk-aac needs wait. The others is already deleted.

**Comment by avibrazil** [comment]
**Chromium** has stopped to support widevine (#21), while out of the box Firefox nicely plays DRM content.
**Kodi** 18 (alpha and unusable) was irresponsibly chosen to be the version included in UnitedRPMs.
**transmission-sequential** is not supported anymore, so I'm going back to qbittorrent.

Its being very hard to find a reason to keep using UnitedRPMs, while plain Fedora and some complements from rpmfusion are perfecty doing the job.

**Comment by kuboosoft** [comment]
@avibrazil avibrazil Kodi update coming soon; Don't worry, please open bug about Kodi if it is unusable. About Chromium, we need people testing it; we applied the fix about it... 

About transmission-sequential; if exist a people helping here, we can enable again our transmission-sequential... Everything has a solution; but a hand is necessary. :ok_hand:

**Comment by avibrazil** [comment]
About Kodi, the bug is the bad decision to put alpha software on the main repo. I’m simply not using it and went back to previous stable version. And it is so inconvenient to manage OS updates while taking care of not updating just Kodi, that I decided to disable UnitedRPMs entirely. Bad decision to use alpha software.

**Comment by kuboosoft** [comment]
@avibrazil Good luck; each one chooses his destiny. :smile:
